apiVersion: v2
name: kodiak
description: Self hosted Kodiak, a bot to automatically update and merge GitHub PRs
keywords:
  - bot
  - github
  - mergebot

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.4

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.54.0

home: https://kodiakhq.com
icon: https://raw.githubusercontent.com/chdsbd/kodiak/v0.20.0/assets/logo.png

sources:
  - https://kodiakhq.com
  - https://github.com/chdsbd/kodiak
  - https://hub.docker.com/r/cdignam/kodiak

dependencies:
  - name: redis
    version: 17.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

maintainers:
  - name: etiennetremel
    email: etienne.tremel@fika.works

annotations:
  # Use this annotation to indicate that this chart version is a pre-release.
  # https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/prerelease: "false"
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/fikaworks/kodiak?modal=changelog
  artifacthub.io/changes: |
    - upgrade role/rolebinding apiVersion and keep backward compatibility
