apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kodiak.fullname" . }}
  labels:
    {{- include "kodiak.labels" . | nindent 4 }}
type: Opaque
data:
  redis-url: {{ include "kodiak.redisUrl" . | b64enc | quote }}
  github-app-id: {{ .Values.githubAppID | b64enc | quote }}
  github-app-name: {{ .Values.githubAppName | b64enc | quote }}
  secret-key: {{ .Values.secretKey | b64enc | quote }}
  kodiak.private-key.pem: {{ .Values.githubPrivateKey | b64enc | quote }}
