{{- if .Values.podSecurityPolicy.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "grgate.fullname" . }}
  labels:
    {{- include "grgate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "grgate.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "grgate.serviceAccountName" . }}
{{- end -}}
