{{- if .Values.podSecurityPolicy.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "grgate.fullname" . }}
  labels:
    {{- include "grgate.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - {{ template "grgate.fullname" . }}-psp
    verbs:
    - use
{{- end -}}
