apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grgate.fullname" . }}
  labels:
    {{- include "grgate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.githubPrivateKey }}
  github.private-key.pem: {{ .Values.githubPrivateKey | b64enc }}
  {{- end }}
  config.yaml: {{ toYaml .Values.config | b64enc }}
