{{- if .Values.podSecurityPolicy.create }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: Role
metadata:
  name: {{ include "kodiak.fullname" . }}
  labels:
    {{- include "kodiak.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - {{ template "kodiak.fullname" . }}-psp
    verbs:
    - use
{{- end -}}
