{{- if .Values.podSecurityPolicy.create }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: RoleBinding
metadata:
  name: {{ include "kodiak.fullname" . }}
  labels:
    {{- include "kodiak.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kodiak.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kodiak.serviceAccountName" . }}
{{- end -}}
