apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kodiak.fullname" . }}
  labels:
    {{- include "kodiak.labels" . | nindent 4 }}
type: Opaque
data:
  redis-url: {{ include "kodiak.redisUrl" . | b64enc | quote }}
  github-app-id: {{ .Values.githubAppID | b64enc | quote }}
  github-app-name: {{ .Values.githubAppName | b64enc | quote }}
  secret-key: {{ .Values.secretKey | b64enc | quote }}
  {{- if .Values.sentryDSN }}
  sentry-dsn: {{ .Values.sentryDSN | b64enc | quote }}
  {{- end }}
  {{- if .Values.githubV3ApiRoot }}
  github-v3-api-root: {{ .Values.githubV3ApiRoot | b64enc | quote }}
  {{- end }}
  {{- if .Values.githubV4ApiUrl }}
  github-v4-api-url: {{ .Values.githubV4ApiUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.githubPrivateKey }}
  kodiak.private-key.pem: {{ .Values.githubPrivateKey | b64enc | quote }}
  {{- end }}

